### ISSUE TITLE
Shortcut for Enabling/Disabling extension

### ISSUE THREAD

**Issue by Daniel-Collins97** [sidp/vscode-strict-whitespace#2]
It would be extremely handy to have a shortcut that enables/disables this extension. When working on code it would be nice to not have the red warning flags at the side of the file and around the whitespace as sometimes this is needed for debugging etc.

When code is complete and you are reviewing to ensure linter errors are not present, this could be turned back on with the shortcut which would then highlight all of the whitespace that can then be removed as seen fit.

Great extension so would be nice to get these couple of features in for it

**Comment by sidp** [comment]
Thank you for the suggestion, @Daniel-Collins97! This has been [added](https://github.com/sidp/vscode-strict-whitespace/commit/d5f576517d5984be6577d973db29559a8221ab04) and will be included in the next release.

**Comment by sidp** [comment]
v0.1.0 has finally been released with this feature.
